import { StyleSheet } from "react-native";

export const style = StyleSheet.create({
  container: {
    marginTop: 30,
    marginLeft: 38,
    marginRight: 28,
    width: 300,
    display: "flex",
    gap: 30,
    flexDirection: "column",
    justifyContent: "center",
  },
  mainHeading: {
    color: "#FFF",
    fontSize: 30,
    textAlign: "center",
    textAlignVertical: "center",
    color: 32,
    lineHeight: 24,
    fontFamily: "Montserrat",
    padding: 10,
  },
  label: {
    fontSize: 14,
    color: " rgba(26, 29, 38, 1)",
    fontFamily: "Montserrat",
    lineHeight: 24,
    fontWeight: 400,
  },
  textField: {
    color: "rgba(204, 204, 204, 1)",
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft:5,
    borderBottomColor: "hsla(0, 0%, 80%, 1)",
    borderBottomWidth: 2,
    width: "100%",
  },
  checkBox: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
    alignItems: "center",
  },
  checkBoxText: {
    width: 200,
    display: "flex",
    justifyContent: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  checkText: {
    fontSize: 10,
    lineHeight: 16,
    fontWeight: 400,
    fontFamily: "hsla(0, 0%, 39%, 1)",
    textAlign: "center",
    textAlignVertical: "center",
  },
  forgotText: {
    fontSize: 12,
    fontFamily: "Montserrat",
    lineHeight: 24,
    fontWeight: 500,
    color: "hsla(225, 19%, 13%, 1)",
  },
  checkBoxInput: {
    width: 15,
    height: 14,
    borderColor: "hsla(0, 0%, 80%, 1)",
  },
  signInBtn: {
    width: 300,
    backgroundColor: "rgba(252, 114, 77, 1)",
    height: 64,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#FFF",
    borderRadius: 6,
    marginTop: 26,
  },
  iconContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 5,
    width: 310,
  },
  iconBox: {
    width: 79,
    height: 58,
    borderColor: "rgba(204, 204, 204, 1)",
    borderRadius: 5,
    borderWidth: 2,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  icon: {
    width: 25,
    height: 25,
  },
  accountText: {
    fontSize: 14,
    lineHeight: 24,
    fontWeight: 500,
    fontFamily:"Montserrat",
    textAlign:"center",
    textAlignVertical:"center"
  },
});
